require 'puppetlabs_spec_helper/rake_tasks'
require 'puppet-lint/tasks/puppet-lint'
require 'puppet-syntax/tasks/puppet-syntax'
require 'ci/reporter/rake/rspec'
require 'rake/clean'

CLEAN.include('spec/fixtures/', 'spec/reports')

task :spec => [:spec_prep, "ci:setup:rspec"]

desc "Run all tasks (spec, syntax, lint)"
task :all => [ :spec, :syntax, :lint ]


PuppetLint.configuration.log_format = "%{path}:%{linenumber}:%{check}:%{KIND}:%{message}"
PuppetLint.configuration.fail_on_warnings = true
PuppetLint.configuration.send("disable_80chars")
